version: '3.8'

services:
  # Serviço da API Python (FastAPI)
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: devops_api_app
    ports:
      - "8000:8000"  # Expondo a porta 8000 da API para o host da VM
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      - PORT=8000
      - DEBUG=${DEBUG:-True}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always
